export const colors = {
  background: "#F4F6FA",
  backgroundElevated: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  surface: "#FFFFFF",
  surfaceSoft: "#F7F8FC",
  card: "#FFFFFF",
  cardAlt: "#FFFFFF",
  cardSoft: "#F8F9FD",
  cardMuted: "#EEF2F8",
  primary: "#F24040",
  primarySoft: "#FFEDEE",
  primaryStrong: "#E13838",
  primaryBorder: "#D93A3A",
  primaryText: "#FFFFFF",
  accent: "#09142D",
  textPrimary: "#09142D",
  textSecondary: "#596275",
  textMuted: "#7A8496",
  textTertiary: "#919BAE",
  muted: "#7A8496",
  success: "#16A36A",
  successSoft: "#E7F7EF",
  warning: "#D47B16",
  warningSoft: "#FFF3DE",
  danger: "#D73B58",
  dangerSoft: "#FFE9EE",
  info: "#2457C5",
  infoSoft: "#E8EEFF",
  border: "#DDE4EF",
  borderSubtle: "#E8EDF5",
  borderSoft: "#CCD5E3",
  overlay: "rgba(9,20,45,0.03)",
  shadow: "#0B1A33",
  webLandingBackground: "#F4F6FA",
  webLandingText: "#09142D",
  webLandingSubtext: "#596275",
  webLandingBorder: "#DDE4EF",
  webLandingPill: "#F7F8FC",
  webLandingAccentPink: "#FF3D57",
  webLandingAccentOrange: "#FF7A00",
  webLandingBrandRed: "#F24040",
  webLandingInputBg: "#FFFFFF",
  // Auth landing aliases for the pre-login marketing screen
  authBackground: "#F4F6FA",
  authSurface: "#FFFFFF",
  authSurfaceSoft: "#F7F8FC",
  authTextPrimary: "#09142D",
  authTextSecondary: "#596275",
  authMuted: "#7A8496",
  authBorder: "#DDE4EF",
  authBorderStrong: "#CCD5E3",
  authBrand: "#F24040",
  authBrandStrong: "#E13838",
  authDanger: "#C43A3A",
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 28,
  xxxl: 36,
} as const;

export const radii = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  pill: 999,
} as const;

export const shadows = {
  card: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 3,
  },
  softCard: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
} as const;
