export const colors = {
  background: "#F6F7FB",
  backgroundElevated: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  surface: "#FFFFFF",
  surfaceSoft: "#F3F4F9",
  card: "#FFFFFF",
  cardAlt: "#FFFFFF",
  cardSoft: "#F7F8FC",
  cardMuted: "#F1F3F7",
  primary: "#F24040",
  primarySoft: "#FFEDEE",
  primaryStrong: "#E13838",
  primaryBorder: "#D93A3A",
  primaryText: "#FFFFFF",
  accent: "#09142D",
  textPrimary: "#09142D",
  textSecondary: "#5E6675",
  textMuted: "#7D8696",
  textTertiary: "#98A0AF",
  muted: "#7D8696",
  success: "#16A36A",
  successSoft: "#E7F7EF",
  warning: "#D47B16",
  warningSoft: "#FFF3DE",
  danger: "#D73B58",
  dangerSoft: "#FFE9EE",
  info: "#2457C5",
  infoSoft: "#E8EEFF",
  border: "#E7EAF1",
  borderSubtle: "#EEF1F6",
  borderSoft: "#D7DDE8",
  overlay: "rgba(9,20,45,0.04)",
  shadow: "#101828",
  webLandingBackground: "#F6F7FB",
  webLandingText: "#09142D",
  webLandingSubtext: "#5E6675",
  webLandingBorder: "#E7EAF1",
  webLandingPill: "#F3F4F9",
  webLandingAccentPink: "#FF3D57",
  webLandingAccentOrange: "#FF7A00",
  webLandingBrandRed: "#F24040",
  webLandingInputBg: "#FFFFFF",
  // Auth landing aliases for the pre-login marketing screen
  authBackground: "#F6F7FB",
  authSurface: "#FFFFFF",
  authSurfaceSoft: "#F3F4F9",
  authTextPrimary: "#09142D",
  authTextSecondary: "#5E6675",
  authMuted: "#7D8696",
  authBorder: "#E7EAF1",
  authBorderStrong: "#D7DDE8",
  authBrand: "#F24040",
  authDanger: "#C43A3A",
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 28,
  xxxl: 36,
} as const;

export const radii = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  pill: 999,
} as const;

export const shadows = {
  card: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 6,
  },
} as const;
